In [1]:
import numpy as np 
import pandas as pd

In [3]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [6]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
credits.shape

(4803, 4)

In [4]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [9]:
movies.shape

(4803, 20)

In [10]:
movies = movies.merge(credits,on='title')

In [11]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
movies.keys

<bound method NDFrame.keys of          budget                                         genres  \
0     237000000  [Action, Adventure, Fantasy, Science Fiction]
1     300000000                   [Adventure, Fantasy, Action]
2     245000000                     [Action, Adventure, Crime]
3     250000000               [Action, Crime, Drama, Thriller]
4     260000000           [Action, Adventure, Science Fiction]
...         ...                                            ...
4779      27000                                       [Comedy]
4787      22000                              [Comedy, Romance]
4797         13                                       [Horror]
4802       7000             [Science Fiction, Drama, Thriller]
4807          0                                             []

                                          homepage      id  \
0                      http://www.avatarmovie.com/   19995
1     http://disney.go.com/disneypictures/pirates/     285
2      http://www.sonypictures.com/movies/spectre/  206647
3               http://www.thedarkknightrises.com/   49026
4             http://movies.disney.com/john-carter   49529
...                                            ...     ...
4779          http://www.miramax.com/movie/clerks/    2292
4787        https://www.facebook.com/DrySpellMovie  255266
4797                 http://tincanmanthemovie.com/  157185
4802                    http://www.primermovie.com   14337
4807                   http://shanghaicalling.com/  126186

                                               keywords original_language  \
0     [culture clash, future, space war, space colon...                en
1     [ocean, drug abuse, exotic island, east india ...                en
2     [spy, based on novel, secret agent, sequel, mi...                en
3     [dc comics, crime fighter, terrorist, secret i...                en
4     [based on novel, mars, medallion, space travel...                en
...                                                 ...               ...
4779           [salesclerk, loser, aftercreditsstinger]                en
4787  [dating, divorce, sex scene, sex comedy, anti ...                en
4797                                    [home invasion]                en
4802  [distrust, garage, identity crisis, time trave...                en
4807                                                 []                en

                                original_title  \
0                                       Avatar
1     Pirates of the Caribbean: At World's End
2                                      Spectre
3                        The Dark Knight Rises
4                                  John Carter
...                                        ...
4779                                    Clerks
4787                                 Dry Spell
4797                               Tin Can Man
4802                                    Primer
4807                          Shanghai Calling

                                               overview  popularity  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577
1     Captain Barbossa, long believed to be dead, ha...  139.082615
2     A cryptic message from Bond’s past sends him o...  107.376788
3     Following the death of District Attorney Harve...  112.312950
4     John Carter is a war-weary, former military ca...   43.926995
...                                                 ...         ...
4779  Convenience and video store clerks Dante and R...   19.748658
4787  Sasha tries to get her soon-to-be ex husband K...    0.048948
4797  Recently dumped by his girlfirend for another ...    0.332679
4802  Friends/fledgling entrepreneurs invent a devic...   23.307949
4807  When ambitious New York attorney Sam is sent t...    0.857008

                                   production_companies  ... runtime  \
0     [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0
1     [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...   169.0
2     [{"name": "Columbia Pictures", "id": 5}, {"nam...  ...   148.0
3     [{"name": "Legendary Pictures", "id": 923}, {"...  ...   165.0
4           [{"name": "Walt Disney Pictures", "id": 2}]  ...   132.0
...                                                 ...  ...     ...
4779  [{"name": "Miramax Films", "id": 14}, {"name":...  ...    92.0
4787                                                 []  ...    90.0
4797  [{"name": "Park Films", "id": 21871}, {"name":...  ...    84.0
4802                 [{"name": "Thinkfilm", "id": 446}]  ...    77.0
4807                                                 []  ...    98.0

                                       spoken_languages    status  \
0     [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1              [{"iso_639_1": "en", "name": "English"}]  Released
2     [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3              [{"iso_639_1": "en", "name": "English"}]  Released
4              [{"iso_639_1": "en", "name": "English"}]  Released
...                                                 ...       ...
4779           [{"iso_639_1": "en", "name": "English"}]  Released
4787           [{"iso_639_1": "en", "name": "English"}]  Released
4797           [{"iso_639_1": "en", "name": "English"}]  Released
4802           [{"iso_639_1": "en", "name": "English"}]  Released
4807           [{"iso_639_1": "en", "name": "English"}]  Released

                                                tagline  \
0                           Enter the World of Pandora.
1        At the end of the world, the adventure begins.
2                                 A Plan No One Escapes
3                                       The Legend Ends
4                  Lost in our world, found in another.
...                                                 ...
4779  Just because they serve you doesn't mean they ...
4787       Getting divorced does funny things to a girl
4797                    Everything You've Heard is True
4802                 What happens if it actually works?
4807                           A New Yorker in Shanghai

                                         title vote_average vote_count  \
0                                       Avatar          7.2      11800
1     Pirates of the Caribbean: At World's End          6.9       4500
2                                      Spectre          6.3       4466
3                        The Dark Knight Rises          7.6       9106
4                                  John Carter          6.1       2124
...                                        ...          ...        ...
4779                                    Clerks          7.4        755
4787                                 Dry Spell          6.0          1
4797                               Tin Can Man          2.0          1
4802                                    Primer          6.9        658
4807                          Shanghai Calling          5.7          7

     movie_id                                               cast  \
0       19995  [{"cast_id": 242, "character": "Jake Sully", "...
1         285  [{"cast_id": 4, "character": "Captain Jack Spa...
2      206647  [{"cast_id": 1, "character": "James Bond", "cr...
3       49026  [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4       49529  [{"cast_id": 5, "character": "John Carter", "c...
...       ...                                                ...
4779     2292  [{"cast_id": 7, "character": "Dante Hicks", "c...
4787   255266  [{"cast_id": 4, "character": "Sasha", "credit_...
4797   157185  [{"cast_id": 1, "character": "Dave", "credit_i...
4802    14337  [{"cast_id": 1, "character": "Aaron", "credit_...
4807   126186  [{"cast_id": 3, "character": "Sam", "credit_id...

                                                   crew
0     [{"credit_id": "52fe48009251416c750aca23", "de...
1     [{"credit_id": "52fe4232c3a36847f800b579", "de...
2     [{"credit_id": "54805967c3a36829b5002c41", "de...
3     [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...                                                 ...
4779  [{"credit_id": "52fe434ac3a36847f8049253", "de...
4787  [{"credit_id": "52fe4ee39251416c911412e7", "de...
4797  [{"credit_id": "54c7851b925141679100372a", "de...
4802  [{"credit_id": "52fe45e79251416c75066791", "de...
4807  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...

[1494 rows x 23 columns]>

In [13]:
import ast

In [14]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [15]:
movies.dropna(inplace=True)

In [16]:

movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

In [17]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]",http://www.avatarmovie.com/,19995,"[culture clash, future, space war, space colon...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[Adventure, Fantasy, Action]",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drug abuse, exotic island, east india ...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[Action, Adventure, Crime]",http://www.sonypictures.com/movies/spectre/,206647,"[spy, based on novel, secret agent, sequel, mi...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[Action, Crime, Drama, Thriller]",http://www.thedarkknightrises.com/,49026,"[dc comics, crime fighter, terrorist, secret i...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[Action, Adventure, Science Fiction]",http://movies.disney.com/john-carter,49529,"[based on novel, mars, medallion, space travel...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [21]:

ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [22]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [23]:
movies['cast'] = movies['cast'].apply(convert)
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [24]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]",http://www.avatarmovie.com/,19995,"[culture clash, future, space war, space colon...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[Adventure, Fantasy, Action]",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drug abuse, exotic island, east india ...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[Action, Adventure, Crime]",http://www.sonypictures.com/movies/spectre/,206647,"[spy, based on novel, secret agent, sequel, mi...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[Action, Crime, Drama, Thriller]",http://www.thedarkknightrises.com/,49026,"[dc comics, crime fighter, terrorist, secret i...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[Action, Adventure, Science Fiction]",http://movies.disney.com/john-carter,49529,"[based on novel, mars, medallion, space travel...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [26]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [27]:
movies.sample(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
2380,25000000,"[Drama, Romance]",http://www.maoslastdancermovie.com/,33870,"[costume, song, village, promise, ballet]",en,Mao's Last Dancer,"At the age of 11, Li was plucked from a poor C...",1.876811,"[{""name"": ""Great Scott Productions Pty. Ltd."",...",...,117.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,最后的舞者,Mao's Last Dancer,6.8,28,33870,"[Chi Cao, Chengwu Guo, Wen Bin Huang]",[Bruce Beresford]
4378,1000000,[Comedy],http://www.orgazmodvd.com/,8675,"[pornography, sex, secret, fight, star, superh...",en,Orgazmo,Joe Young is a devout Mormon living in L.A. tr...,5.065160,"[{""name"": ""Kuzui Enterprises"", ""id"": 2516}, {""...",...,94.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Fighting crime never felt so good!,Orgazmo,6.2,115,8675,"[Trey Parker, Dian Bachar, Matt Stone]",[Trey Parker]
970,50000000,"[Crime, Drama, Thriller]",http://hannibalrising.com/,1248,"[winter, psychopath, horror, serial killer]",en,Hannibal Rising,"The story of the early, murderous roots of the...",6.567065,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,121.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,It started with revenge.,Hannibal Rising,6.0,654,1248,"[Gaspard Ulliel, Aaran Thomas, Gong Li]",[Peter Webber]
3753,4000000,[Thriller],http://www.theboynextdoorfilm.com/,241251,"[male nudity, female nudity, sex, adultery, in...",en,The Boy Next Door,A recently cheated on married woman falls for ...,24.161735,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",...,91.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A Moment She Couldn't Resist. An Obsession He ...,The Boy Next Door,4.1,1022,241251,"[Jennifer Lopez, Ryan Guzman, Ian Nelson]",[Rob Cohen]
4606,0,[Documentary],http://www.51birchstreet.com/index.php,79161,[],en,51 Birch Street,Documentary filmmaker Doug Block had every rea...,0.049921,"[{""name"": ""Copacetic Pictures"", ""id"": 8139}]",...,90.0,[],Released,Do you really want to know your parents?,51 Birch Street,6.8,6,79161,"[Carol Block, Doug Block, Ellen Block]",[Doug Block]

In [28]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [29]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [30]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[Action, Adventure, Fantasy, ScienceFiction]",http://www.avatarmovie.com/,19995,"[cultureclash, future, spacewar, spacecolony, ...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,300000000,"[Adventure, Fantasy, Action]",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drugabuse, exoticisland, eastindiatrad...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,245000000,"[Action, Adventure, Crime]",http://www.sonypictures.com/movies/spectre/,206647,"[spy, basedonnovel, secretagent, sequel, mi6, ...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,250000000,"[Action, Crime, Drama, Thriller]",http://www.thedarkknightrises.com/,49026,"[dccomics, crimefighter, terrorist, secretiden...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,260000000,"[Action, Adventure, ScienceFiction]",http://movies.disney.com/john-carter,49529,"[basedonnovel, mars, medallion, spacetravel, p...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [31]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [32]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [33]:
movies.corr()

C:\Users\91701\AppData\Local\Temp\ipykernel_12332\3313059620.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  movies.corr()

,budget,id,popularity,revenue,runtime,vote_average,vote_count,movie_id
budget,1.000000,-0.057057,0.455004,0.744872,0.369336,0.089521,0.603858,-0.057413
id,-0.057057,1.000000,0.096950,-0.042689,-0.081739,-0.158451,0.011673,0.999788
popularity,0.455004,0.096950,1.000000,0.593674,0.295876,0.301766,0.719989,0.096876
revenue,0.744872,-0.042689,0.593674,1.000000,0.381525,0.251906,0.783619,-0.042843
runtime,0.369336,-0.081739,0.295876,0.381525,1.000000,0.415480,0.441854,-0.081469
vote_average,0.089521,-0.158451,0.301766,0.251906,0.415480,1.000000,0.425256,-0.158244
vote_count,0.603858,0.011673,0.719989,0.783619,0.441854,0.425256,1.000000,0.011441
movie_id,-0.057413,0.999788,0.096876,-0.042843,-0.081469,-0.158244,0.011441,1.000000

In [48]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])

In [49]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,budget,homepage,id,original_language,original_title,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,tags
0,237000000,http://www.avatarmovie.com/,19995,en,Avatar,150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"In the 22nd century, a paraplegic Marine is di..."
1,300000000,http://disney.go.com/disneypictures/pirates/,285,en,Pirates of the Caribbean: At World's End,139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"Captain Barbossa, long believed to be dead, ha..."
2,245000000,http://www.sonypictures.com/movies/spectre/,206647,en,Spectre,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,A cryptic message from Bond’s past sends him o...
3,250000000,http://www.thedarkknightrises.com/,49026,en,The Dark Knight Rises,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,Following the death of District Attorney Harve...
4,260000000,http://movies.disney.com/john-carter,49529,en,John Carter,43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"John Carter is a war-weary, former military ca..."

In [50]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [51]:

vector = cv.fit_transform(new['tags']).toarray()

In [52]:
vector.shape

(1494, 5000)

In [53]:
from sklearn.metrics.pairwise import cosine_similarity

In [54]:
similarity = cosine_similarity(vector)

In [55]:
similarity

array([[1.        , 0.08134892, 0.05423261, ..., 0.        , 0.05504819,
        0.02469324],
       [0.08134892, 1.        , 0.05882353, ..., 0.04428074, 0.        ,
        0.        ],
       [0.05423261, 0.05882353, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.04428074, 0.        , ..., 1.        , 0.        ,
        0.04032389],
       [0.05504819, 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.02469324, 0.        , 0.        , ..., 0.04032389, 0.        ,
        1.        ]])

In [94]:
new[new['title'] == 'The Lego Movie'].index[0]

744

# Recommand Function

In [95]:
def recommend(movie):
    matches = new[new['title'].str.lower() == movie.lower()]

    if matches.empty:
        print(f" We do not have '{movie}' right now. .")
        return

    index = matches.index[0]
    distances = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda x: x[1])

    print(f"Top 5 movies similar to '{movie}':")
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [96]:
recommend('Avatar')

Top 5 movies similar to 'Avatar':
Aliens vs Predator: Requiem
Battle: Los Angeles
Ender's Game
Apollo 18
Edge of Tomorrow

In [97]:
import pickle

In [98]:
pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))